<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'email',
        'emails',
        'phone_number',
        'is_super_admin',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'emails' => 'array',
            'is_super_admin' => 'boolean',
        ];
    }

    /**
     * User's Organizations (with role and position pivot).
     */
    public function organizations(): BelongsToMany
    {
        return $this->belongsToMany(Organization::class, 'organization_user')
                    ->withPivot('role', 'position')
                    ->withTimestamps();
    }

    /**
     * User's Projects (with role and position pivot).
     */
    public function projects(): BelongsToMany
    {
        return $this->belongsToMany(Project::class, 'project_user')
                    ->withPivot('role', 'position')
                    ->withTimestamps();
    }

    /**
     * User's private checklist items.
     */
    public function checklistItems(): HasMany
    {
        return $this->hasMany(ChecklistItem::class);
    }

    /**
     * Activity logs generated by this user.
     */
    public function activityLogs(): HasMany
    {
        return $this->hasMany(ActivityLog::class);
    }

    /**
     * Tasks assigned to this user.
     */
    public function assignedTasks(): HasMany
    {
        return $this->hasMany(Task::class, 'assigned_to');
    }

    /**
     * Wikis authored by this user.
     */
    public function wikis(): HasMany
    {
        return $this->hasMany(Wiki::class, 'author_id');
    }

    /* -----------------------------------------------------------------
     |  Contextual RBAC & Authorization Helpers
     | -----------------------------------------------------------------
     */

    public function isSuperAdmin(): bool
    {
        return (bool) $this->is_super_admin;
    }

    public function canCreateUsers(): bool
    {
        return $this->isSuperAdmin();
    }

    /**
     * Get role in a specific organization.
     */
    public function roleInOrganization(Organization|int $organization): ?string
    {
        $orgId = $organization instanceof Organization ? $organization->id : $organization;
        $pivot = $this->organizations()->where('organization_id', $orgId)->first()?->pivot;

        return $pivot ? $pivot->role : null;
    }

    /**
     * Check if user is an Org Admin in a specific organization.
     */
    public function isOrgAdmin(Organization|int $organization): bool
    {
        if ($this->isSuperAdmin()) {
            return true;
        }

        return $this->roleInOrganization($organization) === 'org_admin';
    }

    /**
     * Get role in a specific project.
     */
    public function roleInProject(Project|int $project): ?string
    {
        $projectId = $project instanceof Project ? $project->id : $project;
        $pivot = $this->projects()->where('project_id', $projectId)->first()?->pivot;

        return $pivot ? $pivot->role : null;
    }

    /**
     * Check if user is a Project Admin in a specific project.
     */
    public function isProjectAdmin(Project $project): bool
    {
        if ($this->isSuperAdmin()) {
            return true;
        }

        if ($this->isOrgAdmin($project->organization_id)) {
            return true;
        }

        return $this->roleInProject($project) === 'project_admin';
    }

    /**
     * Helper to log activity on any model.
     */
    public function logActivity(string $action, string $description, ?Model $subject = null, ?array $properties = null): ActivityLog
    {
        return ActivityLog::create([
            'user_id' => $this->id,
            'action' => $action,
            'description' => $description,
            'subject_type' => $subject ? get_class($subject) : null,
            'subject_id' => $subject?->getKey(),
            'properties' => $properties,
        ]);
    }
}
